### ISSUE TITLE
Angular 10

### ISSUE THREAD

**Issue by blondie63** [ionic-team/ionic-storage#190]
Hi, i've an error after Angular 10 upgrade..
```
[ng] ERROR in node_modules/@ionic/storage/index.d.ts:5:52 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).
[ng] 5     static forRoot(storageConfig?: StorageConfig): ModuleWithProviders;
```

This my code:
```
@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [
    BrowserModule,
    IonicModule.forRoot(),
    IonicStorageModule.forRoot({
      name: '__mydb',
      storeName: '_settings',
      driverOrder: ['sqlite', 'websql', 'indexeddb']
    }),
```
Some help ? :)
Thanks

**Comment by amayvs** [comment]
@blondie63 Duplicate issue - #187

**Comment by mhartington** [comment]
Should be fixed with 2.3.0.

**Comment by zarko-tg** [comment]
2.3.0 seems to break things for Ionic 3.

<img width="823" alt="Screenshot 2020-07-24 at 09 33 16" src="https://user-images.githubusercontent.com/6142411/88369629-bee6c180-cd90-11ea-9271-e59f741193d5.png">

**Comment by amayvs** [comment]
@zarko-tg The error isn't related to Ionic version, it's due to Angular version.

> `ModuleWithProviders` has had the generic type since Angular version 7, but it has been optional.

> Angular version 9 deprecates use of ModuleWithProviders without an explicitly generic type, where the generic type refers to the type of the NgModule.

Ref: https://angular.io/guide/migration-module-with-providers

**Comment by vdcn1** [comment]
I've downgraded my angular version but the error still persist. Tried angular 6, 7, 10. 
![Screenshot_2020-09-28-16-57-23-826_com l2tecnologia sgmapp](https://user-images.githubusercontent.com/26773147/94479971-f6685480-01ab-11eb-9775-f1a528f0c6cf.jpg)

**Comment by tiagotrigger** [comment]
I have a question that is possible to be related to this issue.
I'm using Angular 9 and Webstorm IDE shows this error.

```
Class IonicStorageModule is not and Angular module
```

I'm in a process of migrating a project from Angular 7 and Ionic 4 to Angular 9 or newer and Ionic 5.

![image](https://user-images.githubusercontent.com/3385597/105393899-abab9600-5bfb-11eb-8513-80a37a3c11d9.png)

**Comment by ahmedelatab** [comment]
`npm i @ionic/storage@2.2.0 --save`
